### ISSUE TITLE
[Bug]: plc4c s7 -->many tags in one request will not response 

### ISSUE THREAD

**Issue by kdxq** [apache/plc4x#791] opened 2023-02-08 11:01 UTC
### What happened?

I'm writing a program in plc4c for use in an industrial production environment. Now I have a problem. When there are many tags in a request, there will be no response. I have encountered a similar situation when I used the early version of plc4j, maybe it is pdu and division? Please give some advice, thanks a lot. @chrisdutz 

I used wireshark to capture packets, add the wireshark file include both few tag in one request and response ok, and many tags in one request not response as follow:
[include both response and not.zip](https://github.com/apache/plc4x/files/10685147/include.both.response.and.not.zip)

the screenshot is as follows. Let me know if any information is needed and I will do my best to provide it

![image](https://user-images.githubusercontent.com/43022212/217510288-153e47e4-bc36-4ba0-9fc7-9064abc6289e.png)

### Version

v.0.10.0

### Programming Languages

- [ ] plc4j
- [ ] plc4go
- [X] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [X] S7

**Comment by chrisdutz** [comment] 2023-02-08 12:25
PLC4C was always intended to be a super small implementation of PLC4X drivers, aimed at super tiny embedded computers. For the sake of the size of these drivers, the PLC4X drivers don't have the same set of features the full blown drivers in Java and Go have. 

One of the features the C version is missing, is the query-optimizer, that takes care of transparently splitting up large plc4x requests into multiple smaller S7 requests. How this splitting is done, depends on the type of S7 and the corresponding PDU size. 

When using PLC4C you will have to manually ensure the PDU size of your PLC is not exceeded manually and you'll have to execute multiple separate requests.

**Comment by chrisdutz** [comment] 2023-02-08 12:27
if you're not targeting super tiny embedded devices, I would strongly recommend to have a look at PLC4Go.
Alternatively we are also starting to work on PLC4Rust, but for that not a single driver is yet available. But if you're willing to help implement, there's a lot that can be speed up.

**Comment by kdxq** [comment] 2023-02-08 12:54
Hi,@chrisdutz 
Unfortunately, my project is written in c++, and it has basically been completed. Is plc4c not planning to implement an optimizer? I will try to split the requested into multiple requests.

I'd love to do something for the plc4x, but I'm just an beginner programmer, and if there's anything that needs to be done for testing, or anything else that's within my reach, I'd be happy to do it.

**Comment by chrisdutz** [comment] 2023-02-08 13:17
Well ... I can't say what PLC4X is planning as we are a community. I can just speak for myself, that I'm not planning on doing. it. So for now: I guess splitting up is the way to go for you ... or investigate how to call Go code from C++.

**Comment by chrisdutz** [comment] 2023-02-08 13:17
Well ... as you can imagine ... implementing PLC drivers in C is sort of nothing for the faint of heart. 

Everything is a lot more work in C. 

I implemented this because the EU was financing this work. 

I will not implement features like this, which others need for their production systems for free in my free time ... so unless someone else is willing to help, you plan on doing it or you or your company are willing to pay for it, I'm not seeing this feature coming any time soon.

**Comment by kdxq** [comment] 2023-02-08 13:22
Hi，@chrisdutz 
Thank you very much for all you have done for plc4x. It is a very nice project. I will try your suggestions latter.

**Comment by kdxq** [comment] 2023-02-09 00:52
I retested it. The data of one request are far less than 222 byte, but there will still be similar errors in wireshark, which should not be the problem of pdu.  @chrisdutz

**Comment by kdxq** [comment] 2023-02-09 04:04
Hi, @chrisdutz 
I tested with different data types, such as bool, int and real, and found that if the number of tags is greater than or equal to 40, there will be no response. If it is a pdu-related exception, the number of tags should be related to the data type. Am I right? Could you give some suggestions? As you said yesterday, I want to implement the manual split request，Thank you.

**Comment by chrisdutz** [comment] 2023-02-09 07:03
Well the size of the cotp packet for both the request and the matching response is not allowed to exceed that size.

That's why for example you can't treat even one string without explicitly setting the size, because then the return string would be 255 bytes long and already exceed the size. Doesn't help that the request is way below this size ... please have a look at the class https://github.com/apache/plc4x/blob/develop/plc4j/drivers/s7/src/main/java/org/apache/plc4x/java/s7/readwrite/optimizer/DefaultS7MessageProcessor.java
This contains all the logic the Java version uses to automatically split request ... this should help you understand, what to took for.

**Comment by kdxq** [comment] 2023-02-09 08:43
@chrisdutz 
 Thank you very much.

**Comment by kdxq** [comment] 2023-02-10 03:38
Hi,@chrisdutz
If the PLC data is read in the form of subscription, only when the first subscription is sent request to the PLC? In the following time, is the PLC actively sending data? Can subscription form reduce the number of requests? Am I right?

**Comment by kdxq** [comment] 2023-02-10 03:42
Hi,@chrisdutz
another question.
Can the plc4j achieve the 10ms timed data acquisition task? 
plc4j plc4c plc4go... Is the efficiency of collecting data the same  with the same hardware conditions?

**Comment by thomas169** [comment] 2023-02-10 14:29
https://github.com/apache/plc4x/blob/develop/plc4c/examples/hello-world-s7/src/hello_world_s7_loopback.c
I think this will test loopback time on Linux, as I used PLC4c to read/write to PLC for hardware in the loop type stuff. 
With solid hardware in testing I was able to get ~1ms time. Efficiency of this is 99% depending on hardware, unless you deliberately write code otherwise. Saying that I had started (unfinished) work to make sending/reading the same things repeatedly more deterministic  (less `alloc` use).

**Comment by chrisdutz** [comment] 2023-02-10 14:40
But this tests the Java driver, right? I think the author is explicitly referring to the C version, right? 
I haven't done any analysis, but I would guess it should be able to stay below 10ms for a single request/reply roundtrip. 
However I never tested this. So please ... just try it out.

**Comment by thomas169** [comment] 2023-02-10 14:43
I was referring to C also,  it all I ever used in PLC4x.

**Comment by chrisdutz** [comment] 2023-02-10 14:52
Oh ... I'm so sorry ... didn't even notice we had that example in there ;-)

**Comment by heyoulin** [comment] 2023-02-14 02:21
Try my resp [https://github.com/spnettec/plc4x.git](https://github.com/apache/plc4x/issues/url)? heyoulin branch. I run 2000 tags and no problem

**Comment by kdxq** [comment] 2023-02-17 06:40
hi @heyoulin thanks for your help. i will try it latter. Have you implemented an optimizer for plc4c？

**Comment by chrisdutz** [comment] 2023-02-17 11:51
Hi all ... I would like to say that I'm not too happy with this approach, where @heyoulin forks our repo, changes stuff and then guides people to his repo from the official one. 

@heyoulin it would be awesome, if you would start to creating PRs, so we can possibly integrate these changes back ... because this is not the way open-source should be done.

**Comment by heyoulin** [comment] 2023-02-17 14:37
> 

@chrisdutz I will create some PRs as soon as posible. 
Because many changes i have done. Some changes need many types of PLCs  for verification. Some are experimental modifications. I need time to separate them to independent PR. This will  take a lot of my time.
 I don't mean to guides people to my repo. I have no so many PLCs. I need some people help me to verify using real PLC. 
I want submit a PR after verifying that the PLC is executing correctly.

**Comment by dremsol** [comment] 2023-02-18 16:48
@heyoulin I can give you remote access to a S7300 CPU & S71500 CPU if you like. We could define an address space consisting of different data types and sizes to use for testing.

**Comment by spnettec** [comment] 2023-02-19 10:34
> @heyoulin I can give you remote access to a S7300 CPU & S71500 CPU if you like. We could define an address space consisting of different data types and sizes to use for testing.

@dremsol Thank you. Could you send me the remote ip and address space via email?   heyoulin@gmail.com.

**Comment by kdxq** [comment] 2023-03-10 04:43
hi @heyoulin  @spnettec , I tested your branch. When the number of tags is greater than 40, no data is returned, and all variable types are plclist, and the printed values are bool array, could you give me some suggest? thank you very much.

**Comment by chrisdutz** [comment] 2023-09-22 12:40
So ... is @heyoulin "taking care of this issue"? I would say, that it's actually not a bug, but "works as designed" ... can we close this issue?

**Closed as completed** 2023-09-25 06:21 UTC
