### ISSUE TITLE
Cannot read REAL value from S7-1500 with PLC4J

### ISSUE THREAD

**Issue by floka94** [apache/plc4x#702] opened 2022-12-19 08:49 UTC
I cannot read REAL values from a S7-1500 with PLC4J with version 0.10.0.

I get the following error from the PLC4J Lib:

```bash
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.plc4x.java.s7.readwrite.S7PayloadReadVarResponse.getItems()" because "payload" is null
```

Screenshots from Wireshark:

Request from PLC4J to read REAL:
![image](https://user-images.githubusercontent.com/29139420/208385086-c37a0707-1270-48c3-a2e6-2967925825b1.png)

Response from S7-1500:
![image](https://user-images.githubusercontent.com/29139420/208385171-243090a7-e37f-466a-a59c-c594a9e0676e.png)

**Comment by chrisdutz** [comment] 2022-12-20 08:26
The odd thing is that I have a test with an S7-1200 to test all data-types ... this is a regular data-type which my PLC supports and I couldn't see any problems. 

Also that wireshark can't decode the response sort of seems to indicate that the problem might be your PLC. Is this a genuine Siemens S7-1500 or a clone?

**Comment by floka94** [comment] 2023-01-26 06:37
@chrisdutz this was a simulated S7 with the S7-PLCSIM Advanced V3.0.

**Comment by glcj** [comment] 2023-01-26 16:49
Hi,

Driver version: 0.11.0-SNAPSHOT

For CPU S7-300, work! (%MD100:REAL)
For CPU S7-400, work!
For CPU S7-1214C, work!
For CPU S7-1500,  S7-PLCSIM Advanced V4.0. don't work!

We will have to perform other tests to find out the difference,

**Comment by glcj** [comment] 2023-01-27 02:21
Hi  floka94,

You can check if you have enabled PUT/GET reading on the CPU, you should do that before transferring the project.

If so, please indicate so that the work team can close this point.

For CPU S7-300, work! (%MD100:ACTUAL)
For CPU S7-400, work!
For CPU S7-1214C, work!
For CPU S7-1500, S7-PLCSIM Advanced V4.0. work!

Best regards,

**Comment by floka94** [comment] 2023-01-27 08:36
I updated my code and dependencies

```xml
        <dependency>
            <groupId>org.apache.plc4x</groupId>
            <artifactId>plc4j-api</artifactId>
            <version>0.11.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.apache.plc4x</groupId>
            <artifactId>plc4j-driver-s7</artifactId>
            <version>0.11.0-SNAPSHOT</version>
            <scope>runtime</scope>
        </dependency>
```

It works for other datatypes like BOOL but still not for REAL using S7-PLCSIM Advanced V3.0.

`Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.plc4x.java.s7.readwrite.S7PayloadReadVarResponse.getItems()" because "payload" is null`

**Comment by glcj** [comment] 2023-01-27 17:19
Hello,

I already tested and found no problems:

1. Verify that the DB is not optimized.
2. Verify that the PLC does not have security enabled.
3. Verify that the CPU supports PUT/GET.

I'm preparing a full test run for the S7 driver. I uploaded a simple reading example in [1].

I hope it is useful for you.

1. https://github.com/glcj/PLC4XS7ExamplesV9/blob/0.11.0/src/main/java/com/ceos/plc4x/s7/PLCReadTags.java

**Comment by floka94** [comment] 2023-01-27 17:25
As I already said, it works for any other datatype but not for REAL. So the problem can not be because of the three points you mentioned.

Thank you for the demo project. I will give it a try and inform you.

**Comment by floka94** [comment] 2023-01-28 19:54
Unfortunately the same Exception with your demo project.

```bash
[main] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Instantiating new PLC Driver Manager with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@4b1210ee
[main] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Registering available drivers...
[main] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Registering driver for Protocol s7 (Siemens S7 (Basic))
[main] INFO org.apache.plc4x.java.transport.tcp.TcpChannelFactory - Configuring Bootstrap with Configuration{local-rack=1, local-slot=1, local-tsap=0, remote-rack=0, remote-slot=2, remote-tsap=0, pduSize=1024, maxAmqCaller=8, maxAmqCallee=8, controllerType='null'}
[nioEventLoopGroup-2-1] INFO org.apache.plc4x.java.s7.readwrite.protocol.S7ProtocolLogic - S7 Driver running in ACTIVE mode.
[main] INFO org.apache.plc4x.java.spi.connection.NettyChannelFactory - Channel is closed, closing worker Group also
[main] INFO org.apache.plc4x.java.spi.connection.NettyChannelFactory - Worker Group was closed successfully!
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.apache.plc4x.java.s7.readwrite.S7PayloadReadVarResponse.getItems()" because "payload" is null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.ceos.plc4x.s7.PLCReadTags.main(PLCReadTags.java:32)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.plc4x.java.s7.readwrite.S7PayloadReadVarResponse.getItems()" because "payload" is null
	at org.apache.plc4x.java.s7.readwrite.protocol.S7ProtocolLogic.decodeReadResponse(S7ProtocolLogic.java:765)
	at org.apache.plc4x.java.s7.readwrite.protocol.S7ProtocolLogic.lambda$16(S7ProtocolLogic.java:231)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.apache.plc4x.java.s7.readwrite.protocol.S7ProtocolLogic.lambda$23(S7ProtocolLogic.java:269)
	at org.apache.plc4x.java.spi.Plc4xNettyWrapper.decode(Plc4xNettyWrapper.java:187)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
EventDispacher Bye!
ObjectProcessor Bye!
```

Here is ma recorded pcapng file, I hobe this can help you to find out the problem:
[s7_real.zip](https://github.com/apache/plc4x/files/10528144/s7_real.zip)

**Comment by glcj** [comment] 2023-01-28 21:01
Hello,

In the captures (pcap) you can clearly see that the problem is in the PLCSIM response, specifically the length of the "Data.Item" is 32, when it should be 4 (the length of a real in bytes).

The request job is correct byte for byte, relative to my local test.

The value of 32 would be valid if the "Transport size" were in bits.

For the moment I must point out that the problem is in the PLCSIM.

I did the test with version 4.0 of PLCSIM, please, if you can download and try with this version, you have a 15-day trial license.

I will be careful,
Best regards,

**Comment by heyoulin** [comment] 2023-02-13 16:39
I have tested it. Try  [https://github.com/spnettec/plc4x.git](url) .  heyoun branch

**Comment by chrisdutz** [comment] 2023-09-22 15:27
I did quite a number of updates in the Java S7 driver. Could you please give the current SNAPSHOT another try? However I did test the writing of REAL values with my S7 1200 and that worked flawlessly.

**Comment by ottlukas** [comment] 2024-02-06 10:42
@floka94 can you confirm that this issue can be closed?

**Comment by chrisdutz** [comment] 2024-02-06 12:01
Should be supported now.

**Closed as completed by chrisdutz** 2024-02-06 12:01 UTC

**Comment by NdiayeeCheikh** [comment] 2025-05-08 15:49
Hi you'll
I'm having this issues , what does it mean :
[com.example.plcapp.ModbusClient.main()] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Instantiating new PLC Driver Manager with class loader org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader@323a47fe
[com.example.plcapp.ModbusClient.main()] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Registering available drivers...
[com.example.plcapp.ModbusClient.main()] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Registering driver for Protocol modbus-ascii (Modbus ASCII)
[com.example.plcapp.ModbusClient.main()] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Registering driver for Protocol modbus-rtu (Modbus RTU)
[com.example.plcapp.ModbusClient.main()] INFO org.apache.plc4x.java.DefaultPlcDriverManager - Registering driver for Protocol modbus-tcp (Modbus TCP)
[com.example.plcapp.ModbusClient.main()] INFO org.apache.plc4x.java.transport.serial.SerialChannelFactory - Configuring Bootstrap with org.apache.plc4x.java.transport.serial.DefaultSerialTransportConfiguration@6cac4b00
^C/media/sda4/plc4x/plc-demo #
---------------------------------------------------------------

Here's is my code:
---------------------------------------------------------------
package com.example.plcapp;
import org.apache.plc4x.java.api.PlcDriverManager;
import org.apache.plc4x.java.api.PlcConnection;
import org.apache.plc4x.java.api.messages.PlcReadRequest;
import org.apache.plc4x.java.api.messages.PlcReadResponse;
import java.util.concurrent.TimeUnit;
public class ModbusClient {

    public static void main(String[] args) {
System.out.println("Bonjour");

        // Adapter le port série selon ton système (ex: COM1 sur Windows, /dev/ttyV0 sur Linux)
        String connectionString = "modbus-rtu://dev/ttyV0?baud-rate=9600";
         System.out.println(plcConnection);
       try (PlcConnection plcConnection = PlcDriverManager.getDefault().getConnectionManager().getConnection(connectionString)) {
  

        } catch (Exception e) {
			System.out.println("---------Bonjour---------");
           e.printStackTrace();
        }
    }
}

On the other side, i have a pymodbus server listening :


---------------------------------------------------------------
import asyncio
import logging
from pymodbus.server import StartAsyncSerialServer
from pymodbus.datastore import ModbusServerContext, ModbusSequentialDataBlock, ModbusDeviceContext
from pymodbus import ModbusDeviceIdentification
from pymodbus import __version__ as pymodbus_version

logging.basicConfig(level=logging.INFO)

# Création du datastore avec des données fictives
store = ModbusSequentialDataBlock(0x00, [5] * 100)
block = ModbusSequentialDataBlock(0, [5]*100)
device_context = ModbusDeviceContext(di=block, co=block, hr=block, ir=block)
context = ModbusServerContext(devices=device_context, single=True)
        # Informations d'identité du serveur
identity = ModbusDeviceIdentification()
identity.VendorName = "Pymodbus"
identity.ProductCode = "PM"
identity.VendorUrl = "https://github.com/pymodbus-dev/pymodbus/"
identity.ProductName = "Pymodbus Server"
identity.ModelName = "Modbus Server"
identity.MajorMinorRevision = pymodbus_version

async def run_server():
        await StartAsyncSerialServer(
            context=context,
            identity=identity,
            port="/dev/ttyV0",
            framer="rtu",
            baudrate=9600
        )

if __name__ == "__main__":
    asyncio.run(run_server())
